# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# 2016/17
# gem 'prawn', '~> 2.1.0'
# gem 'prawn-table', '~> 0.2.2'

# 2017/18
gem 'prawn', '~> 2.2.2'
gem 'prawn-table', '~> 0.2.2'
